apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ci-cd-demo
  template:
    metadata:
      labels:
        app: ci-cd-demo
    spec:
      containers:
        - name: ci-cd-demo
          image: ybodagala/ci-cd-demo:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-demo-service
spec:
  type: NodePort
  selector:
    app: ci-cd-demo
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
